/**
 * The in-app architecture modal.
 *
 * Five tabs, each pairing one theme-aware SVG with a bilingual explanation. The SVGs are GENERATED by
 * `scripts/build_architecture_svgs.py` from the committed artifacts, so their numbers cannot disagree
 * with the data and their boxes size themselves from their text; the test suite runs the generator in
 * check mode. They live under `public/svg/tech/`, are fetched and inlined by the shell so their
 * colours repaint with the theme, and carry both languages as two complete layouts.
 *
 * The explanations say what the drawings show and avoid numbers that move with a bake; the numbers
 * are on the drawings and on the pages, read from the artifacts.
 */

import type { ArchitectureConfig } from '@fasl-work/caos-app-shell';

export const architecture: ArchitectureConfig = {
  title_en: 'Architecture and how it works',
  title_es: 'Arquitectura y cómo funciona',
  tabs: [
    {
      id: 'what',
      en: 'What this is',
      es: 'Qué es esto',
      svg: 'svg/tech/01-the-app.svg',
      body_en: `Fragmenta predicts the mean fragment size of a bench blast from its design and its rock, with ten
published predictors from the 1973 classical equation to the 2025 stacking ensemble, and measures what
each prediction is worth at a mine the model has not seen. The data are 97 published bench blasts from
ten campaigns in five countries, two published hold-outs and five field blasts.

Every predictor is scored three ways: a hundred random 80/20 splits, a hundred splits after collapsing
the repeated input vectors, and ten hold-outs of a whole campaign each, with an interval obtained by
resampling campaigns. Every score is variance explained about the identity line, shown with the squared
correlation the literature reports and with a null model that predicts the training mean.

What it is not: no mechanistic simulation, no non-ideal detonation, no flyrock or vibration, and no
downstream comminution model. Constants that no source prints are user parameters.`,
      body_es: `Fragmenta predice el tamaño medio de fragmento de una voladura de banco a partir de su diseño y de su
roca, con diez predictores publicados que van de la ecuación clásica de 1973 al ensamble apilado de
2025, y mide cuánto vale cada predicción en una mina que el modelo no ha visto. Los datos son 97 tiros
de banco publicados de diez campañas en cinco países, dos conjuntos de validación publicados y cinco
tiros de campo.

Cada predictor se puntúa de tres formas: cien particiones aleatorias 80/20, cien particiones tras
colapsar los vectores de entrada repetidos, y diez retenciones de una campaña completa cada una, con un
intervalo obtenido remuestreando campañas. Cada puntaje es varianza explicada respecto de la línea de
identidad, junto a la correlación al cuadrado que reporta la literatura y a un modelo nulo que predice
la media de entrenamiento.

Lo que no es: sin simulación mecanicista, sin detonación no ideal, sin proyección de rocas ni
vibración, y sin modelo de conminución aguas abajo. Las constantes que ninguna fuente imprime son
parámetros del usuario.`,
    },
    {
      id: 'lanes',
      en: 'Where it runs',
      es: 'Dónde corre',
      svg: 'svg/tech/02-lanes.svg',
      body_en: `Offline runs everything that fits or measures, against pinned versions: the per-case training, the
random and deduplicated draws, the ten site hold-outs, the intervals and the diagnostics. The science
lives in a separately published engine package that this product pins and consumes.

The committed artifacts are what the web replays: one file per case, one benchmark file, and one file of
fitted models per training scope, each content-addressed and listed with its digest in an index.

In the browser two lanes recompute live. The closed forms are written in TypeScript and tested for
parity against every baked blast. The fitted learned models are walked from their exported form and
tested against the original models' predictions at every shipped blast: exactly for the tree models,
to a relative 1e-12 for the network and the kernels. The deploy copies the artifacts and checks their
digests; it never trains and never recomputes a benchmark.`,
      body_es: `Sin conexión corre todo lo que ajusta o mide, con versiones fijadas: el entrenamiento por caso, los
sorteos aleatorios y deduplicados, las diez retenciones de sitio, los intervalos y los diagnósticos.
La ciencia vive en un paquete motor publicado aparte que este producto fija y consume.

Los artefactos comprometidos son lo que la web reproduce: un archivo por caso, un archivo de benchmark
y un archivo de modelos ajustados por alcance de entrenamiento, cada uno direccionado por contenido y
listado con su resumen en un índice.

En el navegador se recalculan dos carriles en vivo. Las formas cerradas están escritas en TypeScript y
se prueban por paridad contra cada tiro horneado. Los modelos aprendidos ajustados se recorren desde su
forma exportada y se prueban contra las predicciones de los modelos originales en cada tiro publicado:
exactamente para los modelos de árboles, con una diferencia relativa de 1e-12 para la red y los núcleos.
El despliegue copia los artefactos y verifica sus resúmenes; nunca entrena ni recalcula un benchmark.`,
    },
    {
      id: 'web',
      en: 'The web flow',
      es: 'El flujo web',
      svg: 'svg/tech/03-web-flow.svg',
      body_en: `The App route is a workbench for one selected case: a rail with the case and arm selectors, and six tabs
grouped by the question a reader asks rather than by the list of models. The What if tab recomputes every
arm, learned ones included, on a design you change, from the models fitted for that case without its
own campaign.

Introduction, Methodology and Implementation explain the problem, every predictor and how the numbers
are produced. Experiments and Benchmark are the only routes that summarise across cases.

The focus view shows one case full screen outside the header and footer, and applies the theme itself.
Every chart reads values under the pointer, in a readout line under the drawing.`,
      body_es: `La ruta App es un taller para un caso seleccionado: un riel con los selectores de caso y de brazo, y
seis pestañas agrupadas por la pregunta del lector y no por la lista de modelos. La pestaña Qué pasa si
recalcula todo brazo, aprendidos incluidos, sobre un diseño que usted cambia, con los modelos ajustados
para ese caso sin su propia campaña.

Introducción, Metodología e Implementación explican el problema, cada predictor y cómo se producen los
números. Experimentos y Benchmark son las únicas rutas que resumen entre casos.

La vista de foco muestra un caso a pantalla completa fuera del encabezado y el pie, y aplica el tema
por sí misma. Cada gráfico lee valores bajo el puntero, en una línea de lectura bajo el dibujo.`,
    },
    {
      id: 'science',
      en: 'The science flow',
      es: 'El flujo científico',
      svg: 'svg/tech/04-the-science.svg',
      body_en: `The corpus publishes seven ratios and no dimensions, and the classical equation needs a rock volume and
a charge mass per hole. The source prose gives a hole diameter for eight of its ten sites, a ninth comes
from its stated bench height, and the reconstruction is checked against fifteen dimensional constraints
the same prose states. The tenth site publishes nothing absolute and every arm that needs a volume
abstains there with a reason.

The rock factor both source papers say they estimated, and neither printed, is recovered by inverting
the equation on the published predictions, and it barely moves within a site. A transfer form predicts
it from Young's modulus with a line fitted over the training sites only, so the classical arm can be
scored on a site without any information about that site, and it scores almost the same.

The predictors then run under the three protocols, each one declaring what it was fitted on: the router
and the published regression were fitted by their source on the corpus itself and are reported in
sample.`,
      body_es: `El corpus publica siete razones y ninguna dimensión, y la ecuación clásica necesita volumen de roca y
masa de explosivo por barreno. La prosa de la fuente da un diámetro de perforación en ocho de sus diez
sitios, un noveno sale de su altura de banco declarada, y la reconstrucción se comprueba contra quince
restricciones dimensionales que la misma prosa declara. El décimo sitio no publica nada absoluto y todo
brazo que necesita un volumen se abstiene allí con una razón.

El factor de roca que ambos artículos dicen haber estimado, y ninguno imprimió, se recupera invirtiendo
la ecuación sobre las predicciones publicadas, y casi no varía dentro de un sitio. Una forma de
transferencia lo predice desde el módulo de Young con una recta ajustada solo sobre los sitios de
entrenamiento, así que el brazo clásico se puede puntuar en un sitio sin información de ese sitio, y
puntúa casi lo mismo.

Los predictores corren entonces bajo los tres protocolos, cada uno declarando con qué se ajustó: el
enrutador y la regresión publicada los ajustó su fuente sobre el propio corpus y se informan dentro de
la muestra.`,
    },
    {
      id: 'contracts',
      en: 'The two contracts',
      es: 'Los dos contratos',
      svg: 'svg/tech/05-data-contracts.svg',
      body_en: `Contract 1 decides what gets in. A value outside the contract range is an entry or unit error and is
rejected; a value outside the training envelope is admitted only on an explicit opt-in and every
prediction made on it is stamped as an extrapolation. Nothing is clipped. Behind it, the integrity gate
reproduces the source paper's own summary table from the shipped rows and compares a pinned digest; it
found five transcription errors in the corpus as first assembled, two on the measured size.

Contract 2 decides what goes out: case, benchmark and model files, each content-addressed and listed with
its digest. The browser's typed mirror names every field the artifacts carry, and a field that appears
on one side only fails the tests. The release gate re-reads and re-hashes every file, checks that every
predicted cell carries a number or a reason, and checks that each case points at the models of its own
training scope.`,
      body_es: `El contrato 1 decide qué entra. Un valor fuera del rango del contrato es un error de captura o de
unidad y se rechaza; un valor fuera de la envolvente de entrenamiento se admite solo con un permiso
explícito y toda predicción hecha sobre él queda sellada como extrapolación. Nada se recorta. Detrás,
la compuerta de integridad reproduce la tabla resumen del propio artículo desde las filas enviadas y
compara un resumen fijado; encontró cinco errores de transcripción en el corpus tal como se ensambló
primero, dos sobre el tamaño medido.

El contrato 2 decide qué sale: archivos de caso, de benchmark y de modelos, cada uno direccionado por
contenido y listado con su resumen. El espejo tipado del navegador nombra cada campo que traen los
artefactos, y un campo que aparece de un solo lado hace fallar las pruebas. La compuerta de
publicación relee y vuelve a calcular el resumen de cada archivo, comprueba que cada celda predicha
lleve un número o una razón, y que cada caso apunte a los modelos de su propio alcance de entrenamiento.`,
    },
  ],
};
